return {
  'folke/which-key.nvim',
  event = 'VimEnter', -- Sets the loading event to 'VimEnter'

  opts = {
    -- delay between pressing a key and opening which-key (milliseconds)
    -- this setting is independent of vim.o.timeoutlen
    delay = 0,
    icons = {
      -- set icon mappings to true if you have a Nerd Font
      mappings = vim.g.have_nerd_font,
      -- If you are using a Nerd Font: set icons.keys to an empty table which will use the
      -- default which-key.nvim defined Nerd Font icons, otherwise define a string table
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },

    -- Document existing key chains
    spec = {
      { '<leader>s', group = '[C]WD' },
      { '<leader>s', group = '[S]earch' },
      { '<leader>n', group = '[N]otes' },
      { '<leader>nt', group = '+[T]emplates' },
      { '<leader>g', group = '[G]it', mode = { 'n', 'v' } },
      { '<leader>gd', group = '+[D]iffs', mode = { 'n', 'v' } },
      { '<leader>gh', group = '+[H]unks', mode = { 'n', 'v' } },
      { '<leader>gH', group = '+Git[H]ub', mode = { 'n', 'v' } },
      { '<leader>gv', group = '+Diff[v]iew', mode = { 'n', 'v' } },
      { '<leader>h', group = '[H]TTP (Bruno)' },
      { '<leader>he', group = '+[E]nv' },
      { '<leader>L', group = '[L]ua' },
      { '<leader>m', group = '[M]arks' },
      { '<leader>M', group = '[M]arkdown' },
      { '<leader>t', group = '[T]abs' },
      { '<leader>w', group = '[W]ezterm' },
      { '<leader>r', group = '[R]eplace' },
      { '<leader>k', group = 'Pee[k]' },
      { '<leader>z', group = 'Close' },
      { '<leader>p', group = '[P]aths', mode = { 'n', 'v' } },
      { '<leader>P', group = '[P]aste', mode = { 'n', 'v' } },
      { '<leader><leader>', group = 'Extended Commands' },
      { '<leader><leader>s', group = '[S]urround' },
      { '<leader><leader>o', group = '[O]ptions' },
      { '<leader><leader>of', group = '+[F]ormatter (Conform)' },
      { '<leader>b', group = 'De[b]ug', mode = { 'n', 'v' } },
      { '<leader>e', group = '[E]rror' },
      { '<leader>S', group = '[S]cratch/[S]wap', mode = { 'n', 'v' } },
      { '<leader>a', group = '[A]I', mode = { 'n', 'v' } },
      { '<leader>ao', group = '+[O]pencode', mode = { 'n', 'v' } },
      { '<leader>ac', group = '+[C]odeCompanion', mode = { 'n', 'v' } },
    },
  },
}
